### ISSUE TITLE
enable dynamic dhcp pools for IPI installs

### ISSUE THREAD

**Issue by walidshaari** [redhat-cop/ocp4-helpernode#144]
the current dhcpd.conf restricts ips to only mapped/reserved mac addresses, for IPI install, it requires the standard ip addressing, the issues is the deny unknown-clients inside the only pool of addresses.

**Comment by walidshaari** [comment]
there are several way to resolve this, either remove this directive or add possibly another pool for dynamic? easiest is remove

**Comment by christianh814** [comment]
This could be done by just making it a variable in the dhcp section...example...

```
dhcp:
  router: "192.168.7.1"
  bcast: "192.168.7.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.7.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
  denyunknown: true
```

Then in the dhcpd.conf jn2 file we could have something like (or whatever makes sense)

```
{% if dhcp.denyunknown %}
		deny unknown-clients; 
{% else %}
		# deny unknown-clients;
{% endif %}
```
